### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by thedotedge** [sapegin/social-likes-next#1]
It would be great if it would be possible to get it via bower like the previous version.

**Comment by sapegin** [comment]
You can use [npmcdn](https://npmcdn.com/) for Bower.

**Comment by thedotedge** [comment]
Yeah, I saw that, but I'd like to bundle js and css with into existing minified files produced by project build.

**Comment by sapegin** [comment]
Then use npm, Bower is dead.
