### ISSUE TITLE
Cannot align center

### ISSUE THREAD

**Issue by 2braincells2go** [sapegin/social-likes-next#11]
Hi. Very nice sharing script! Very light and simple to use.

I am using on a bootstrap template and cannot get the div to align center. Have used proper Bootstrap CSS  to align row/column and everything in container aligns center except the class social-likes. Downloaded the CSS but still cannot find how to align center.

Using:

`<div class="social-likes">
<div data-service="facebook" title="Share link on Facebook">Facebook</div>
<div data-service="twitter" title="Share link on Twitter">Twitter</div>
<div data-service="plusone" title="Share link on Google+">Google+</div>
<div data-service="pinterest" title="Share link on Pinterest">Pinterest</div>
<div data-service="linkedin" title="Share link on LinkedIn">LinkedIn</div>
</div>`

Thanks in advance for any input.

**Comment by sapegin** [comment]
Check how it’s don on the [demo site](http://social-likes-next.js.org/).
